# Generated by Django 4.1.6 on 2023-02-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=56)),
                ('phone', models.CharField(max_length=10)),
                ('country_code', models.CharField(max_length=3)),
            ],
        ),
    ]
